import AppIcon from "@assets/svgs/icon.svg"
import Telegram from "@assets/svgs/telegram.svg"
import {
  AlertCircle,
  AlertTriangle,
  ArrowDownNarrowWide,
  ArrowRight,
  ArrowUpNarrowWide,
  BadgeHelp,
  BadgeMinus,
  Briefcase,
  Calendar,
  Check,
  CheckCheck,
  CheckCircle,
  CheckCircle2,
  ChevronDown,
  ChevronRight,
  CircleDotDashed,
  CircleUserRound,
  DollarSign,
  Download,
  ExternalLink,
  File,
  FileText,
  FileVideo,
  Film,
  Filter,
  FolderOpen,
  Fullscreen,
  Image,
  Images,
  Info,
  KeyRound,
  LayoutDashboard,
  LogOut,
  MailCheck,
  MapPin,
  Megaphone,
  Moon,
  MoreHorizontal,
  PackageOpen,
  PencilLine,
  Plus,
  Presentation,
  Radar,
  Receipt,
  Scale,
  Search,
  Settings,
  Star,
  SunMedium,
  TableProperties,
  TimerReset,
  Trash2,
  Upload,
  UploadCloud,
  User,
  View,
  XCircle,
} from "lucide-react"

export type IconKeys = keyof typeof icons

type IconsType = {
  [key in IconKeys]: React.ElementType
}

const icons = {
  sun: SunMedium,
  moon: Moon,
  check: Check,
  mailCheck: MailCheck,
  keyRound: KeyRound,
  checkCheck: CheckCheck,
  checkCircle: CheckCircle,
  chervonRight: ChevronRight,
  chervonDown: ChevronDown,
  fileText: FileText,
  circleDotDashed: CircleDotDashed,
  xCircle: XCircle,
  circleUserRound: CircleUserRound,
  settings: Settings,
  logout: LogOut,
  search: Search,
  file: File,
  fileVideo: FileVideo,
  download: Download,
  upload: Upload,
  uploadCloud: UploadCloud,
  user: User,
  moreHorizontal: MoreHorizontal,
  trash2: Trash2,
  alertCircle: AlertCircle,
  alertTriangle: AlertTriangle,
  dollarSign: DollarSign,
  packageOpen: PackageOpen,
  arrowRight: ArrowRight,
  layoutDashboard: LayoutDashboard,
  badgeHelp: BadgeHelp,
  folderOpen: FolderOpen,
  receipt: Receipt,
  star: Star,
  briefcase: Briefcase,
  externalLink: ExternalLink,
  filter: Filter,
  calendar: Calendar,
  view: View,
  presentation: Presentation,
  tableProperties: TableProperties,
  image: Image,
  film: Film,
  arrowUpNarrowWide: ArrowUpNarrowWide,
  arrowDownNarrowWide: ArrowDownNarrowWide,
  info: Info,
  pencilLine: PencilLine,
  plus: Plus,
  checkCircle2: CheckCircle2,
  appIcon: AppIcon,
  timerReset: TimerReset,
  scale: Scale,
  megaphone: Megaphone,
  images: Images,
  badgeMinus: BadgeMinus,
  telegram: Telegram,
  fullScreen: Fullscreen,
  mapPin: MapPin,
}

export const Icons: IconsType = icons
